# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 'Install jpm'
    - run: npm install jpm --global
    
    - name: 'Build'
    - run: jpm -v --stop-on-error xpi
      
    # Upload a single file artifact
    - name: 'Upload artefact#1'
      uses: ./
      with:
        name: 'play-it-mpv'
        path: /home/runner/work/play-it-mpv/play-it-mpv/play-it-mpv.xpi
      
